version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15.6
    working_directory: /mnt/ramdisk
    environment:
      GOMODCACHE: /mnt/ramdisk/go_modules
      GOCACHE: /mnt/ramdisk/go_build_cache
    steps:
      - checkout
      # - run: sudo apt install upx-ucl # add this back to use upx
      - run: go test
      - run: goreleaser
      - run: curl -sL https://git.io/goreleaser | bash
      - run: du -h dist/*
      - store_artifacts:
          path: ./dist
