version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.15.6
    working_directory: /mnt/ramdisk
    environment:
      GOMODCACHE: /mnt/ramdisk/go_modules
      GOCACHE: /mnt/ramdisk/go_build_cache
    steps:
      - checkout
      - run: sudo apt install upx-ucl
      - run: go test
      - run: GOOS=linux go build -ldflags="-s -w" -o="./build/linux/hash-stuff" cmd/hash-stuff/main.go && upx --brute ./build/linux/hash-stuff
      # - run: GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o="./build/darwin/hash-stuff" cmd/hash-stuff/main.go && upx --brute ./build/darwin/hash-stuff
      - run: du -h build
      - store_artifacts:
          path: ./build
